#!/usr/bin/env sh

cabal_found=false

for f in *; do
  if [[ -f "${f}" ]]; then
    if [[ "${f}" == "Cargo.toml" ]]; then
      cargo "$@"
    fi
    if [[  "${cabal_found}" == false && "${f}" == *.cabal ]]; then
      cabal_found=true
      cabal "$@"
    fi
  fi
done
